name: Lint

on:
  - push
  - pull_request

env:
  CGO_LDFLAGS_ALLOW: "-s|-w"

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: darthsim/imgproxy-ci:202407111824
    strategy:
      matrix:
        go-version: ["1.22.x"]
        vips-version: ["8.15"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Download mods
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.57.2
          args: --timeout 5m0s
          skip-cache: true
        env:
          LD_LIBRARY_PATH: "/usr/local/lib:/root/vips/${{ matrix.vips-version }}/lib"
          PKG_CONFIG_PATH: "/usr/local/lib/pkgconfig:/root/vips/${{ matrix.vips-version }}/lib/pkgconfig"

  c-lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          version: 18 # Ubuntu 24.04 provides clang-format-18
          tidy-checks: '-*' # disable clang-tidy

      - name: Fail fast
        continue-on-error: true # TODO: remove this line in the future
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
